[project]
name = "would-you-slug"
version = "0.0.1"
dependencies = [
  "adafruit_blinka_displayio==0.11.1",
  "adafruit_circuitpython_display_text==3.2.2",
  "blinka_displayio_pygamedisplay==2.4.0",
  "pygame==2.6.1",
  "typing-extensions==4.12.2",
]
